CREATE DOMAIN TString VARCHAR(80);
CREATE DOMAIN TDateTime TIMESTAMP;
CREATE DOMAIN TDouble DECIMAL(10, 2);
CREATE DOMAIN TInteger INTEGER;
CREATE DOMAIN TPhone CHAR(11);

CREATE SEQUENCE GEN_FUNCIONARIO;
CREATE SEQUENCE GEN_DEPARTAMENTO;

CREATE TABLE FUNCIONARIO
    (
        ID TInteger PRIMARY KEY,
        NOME TString,
        ADMISSAO TDateTime,
        SALARIO TDouble
    );

CREATE TABLE DEPARTAMENTO
    (
        ID TInteger PRIMARY KEY,
        DESCRICAO TString,
        TELEFONE TPhone
    );

CREATE TABLE FUNCIONARIO_DEPARTAMENTO
    (
        FUNCIONARIO_ID TInteger NOT NULL REFERENCES FUNCIONARIO(ID),
        DEPARTAMENTO_ID TInteger NOT NULL REFERENCES DEPARTAMENTO(ID)
    );